// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOJx7PEZkAef34C01TSPQDDLRzuCY6s-Q',
    appId: '1:763452816451:web:eb717952e4d51daacb28f6',
    messagingSenderId: '763452816451',
    projectId: 'kfcc-1d3e8',
    authDomain: 'kfcc-1d3e8.firebaseapp.com',
    storageBucket: 'kfcc-1d3e8.appspot.com',
    measurementId: 'G-9VQ16GMFEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClcYHiLAOVAR4gyhE558VMULIEDR5SydM',
    appId: '1:763452816451:android:191cb31168ffc2f2cb28f6',
    messagingSenderId: '763452816451',
    projectId: 'kfcc-1d3e8',
    storageBucket: 'kfcc-1d3e8.appspot.com',
  );
}
